package com.laboratorio.entrega.razasypelejesdiazduhour;

enum RazayPelaje {
    PETISO_ARGENTINO_FIN_ROSILLO,
    MESTIZO_CRUZA_ARABE_FIN_ALAZAN_TOSTADO,
    SANGRE_PURA_CARRERA_FIN_ZAIN_COLORADO,
    MESTIZO_OVERO_FIN_ZAINO,
    MESTIZO_FIN_ALAZAN_RUANO,
    MESTIZO_FIN_BLANCO,
    MESTIZO_QH_CON_CRIOLLO_FIN_OVERO_AZULEJO,
    MESTIZO_FIN_ALAZAN,
    MESTIZO_FIN_TOBIANO,
    MESTIZO_FIN_TORDILLO_CANELA,
    MESTIZO_FIN_ZAINO,
    CRIOLLO_FIN_PICASO,
    CURATO_DE_MILLA_FIN_BAYO,
    PETISO_ARGENTINO_FIN_TORDILLO_MORO,
    MESTIZO_FIN_OVERO_ROSADO,
    MESTIZO_FIN_MORO,
    PETISO_ARGENTINO_FIN_ZAINO,
    MESTIZO_FIN_ALAZAN_PINTADO,
    SILLA_ARGENTINO_FIN_ALAZAN,
    CRIOLLO_FIN_BAYO_GATEADO,
    MESTIZO_FIN_ZAINO_OSCURO,
    MESTIZO_FIN_TORDILLO;

}
